version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:latest
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-balance:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: ./user-balance
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env