version: '3.8'

services:
  todo-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    networks:
            new:
                aliases:
                    - database
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
  migrate:
        image: migrate/migrate
        networks:
            - new
        volumes:
            - .:/migrations
        command: ["-path", "./schema", "-database",  "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable", "up", "3"]
        links: 
            - db
networks:
      new: